apiVersion: v1
kind: Pod
metadata:
 name: alpine-test       
spec:
 containers:
 - name: alpine
   image: alpine
   env:
    - name: GREETING_MSG
      value: "Hello from environment variable"
    - name: APP_NAME
      value: "Alpine Test"