apiVersion: v1
kind: Pod
metadata:
 name: alpine-test       
spec:
 containers:
 - name: alpine
   image: goutamsh/springboot-with-docker
   command: ["printenv"]
   args: ["GREETING_MSG", "APP_NAME"]
   restartPolicy: OnFailure
   env:
    - name: GREETING_MSG
      value: "Hello from environment variable"
    - name: APP_NAME
      value: "Alpine Test"